learn/urls.py
from django.conf.urls import patterns, url

from learn import views

urlpatterns = patterns('',
        # eg: /learn/
        url(r'^$', views.index, name='index'),
        # eg: /learn/word/
        url(r'^(?P<word>[a-zA-Z]+)/$', views.learn_word, name='learn_word'),
)

puzzles/urls.py
from django.conf.urls import patterns, url

from puzzles import views

urlpatterns = patterns('',
        # eg: /puzzles/
        url(r'^$', views.puzzle_get, name='index'),

        # eg: /puzzles/5/
        url(r'^(?P<puzzle_id>\d+)/$', views.puzzle_id, name='puzzle'),

        # eg: /puzzles/random/
        url(r'^random/$', views.puzzle_random, name='random'),

        # eg: /puzzles/_create/word/
        url(r'^_create/(?P<word>[a-zA-Z]+)/$', views.puzzle_create, name='create'),

        # eg: /puzzles/_get/
        url(r'^_get/$', views.puzzle_get, name='get'),

        # eg: /puzzles/left/right/
        url(r'^(?P<left>[a-zA-Z]+)/(?P<right>[a-zA-Z]+)/$', views.puzzle_by_words, name='puzzle_by_words'),

        # eg: /puzzles/5/answer
        url(r'^(?P<puzzle_id>\d+)/answer/$', views.answer, name='answer'),
)

wordlinks/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wordlinks.views.home', name='home'),
    # url(r'^wordlinks/', include('wordlinks.foo.urls')),

    url(r'^learn/', include('learn.urls', namespace='learn')),
    url(r'^words/', include('words.urls', namespace='words')),
    url(r'^puzzles/', include('puzzles.urls', namespace='puzzles')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

puzzles/models.py
from django.db import models
from django.db.models import F
from words.models import Word

class WrongAnswerException(Exception):
        pass

class Puzzle(models.Model):
    left = models.ForeignKey(Word, related_name='left+')
    right = models.ForeignKey(Word, related_name='right+')
    views = models.PositiveIntegerField(default=0)
    attempts =  models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.left.word + ' / ' + self.right.word

    def get_absolute_url(self):
        ## from django.core.urlresolvers import reverse
        return "/puzzles/%s/%s/" % (self.left, self.right);
        ## return reverse('puzzles.views.puzzle_by_words',
        ##     args=(self.left.word, self.right.word))

    def answer(self, word):
        self.attempts = self.attempts + 1
        self.save()
        answer, created = Answer.objects.get_or_create(puzzle=self, answer = word)
        answer.make_links()
        answer.attempts = F('attempts') + 1
        answer.save()
        return Answer.objects.get(pk=answer.pk)

    class Meta:
        unique_together = ('left', 'right')

class Answer(models.Model):
    puzzle = models.ForeignKey(Puzzle, related_name='answers')
    answer = models.ForeignKey(Word)
    attempts = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.puzzle.left.word + ' * ' + self.answer.word + ' * ' + self.puzzle.right.word

    @property
    def is_verified(self):
        link1, link2 = self.get_links()
        return (
            self.puzzle.left.is_verified and
            self.puzzle.right.is_verified and 
            self.answer.is_verified and
            link1.is_verified and
            link2.is_verified
        )

    @property
    def is_rejected(self):
        link1, link2 = self.get_links()
        return (
            self.puzzle.left.is_rejected or
            self.puzzle.right.is_rejected or 
            self.answer.is_rejected or
            link1.is_rejected or
            link2.is_rejected
        )

    def make_links(self):
        return self.get_links();

    def get_links(self):
        from words.models import WordLink
        link1, created1 = WordLink.objects.get_or_create(predecessor = self.puzzle.left, successor = self.answer)
        link2, created2 = WordLink.objects.get_or_create(predecessor = self.answer, successor = self.puzzle.right)
        return (link1, link2)

    def verify():
        # approving an answer means first approving the component words if
        # necessary: 
        self.puzzle.left.verify();
        self.puzzle.left.save();
        self.puzzle.right.verify();
        self.puzzle.right.save();
        self.answer.verify();
        self.answer.save();

        ## then the two links A -> B and B -> C need to be created if necessary
        ## and also approved: 
        link1, link2, c1, c2 = self.get_links()
        link1.verify();
        link2.verify();
        link1.save();
        link2.save();
        
        ## the actual answer object (self) doesn't change at all.

    class Meta:
        unique_together = ('puzzle', 'answer')

puzzles/views.py
from django import forms
from django.forms import widgets
from django.shortcuts import render, redirect, get_object_or_404
from puzzles.models import Puzzle, Answer, WrongAnswerException
from words.models import Word

# Create your views here.

# TODO: remove most of these views. keep puzzle_get as entrypoint

def index(request):
    puzzles = Puzzle.objects.all().order_by('?')[:10]
    return render(request, 'puzzles/index.html', {'puzzles': puzzles})

def puzzle_show(request, puzzle):
    form = PuzzleForm();
    return render(request, 'puzzles/puzzle.html',
        {'puzzle': puzzle, 'form': form })

def puzzle_id(request, puzzle_id):
    puzzle = get_object_or_404(Puzzle, pk=puzzle_id)
    return puzzle_show(request, puzzle)

def puzzle_by_words(request, left, right):
    w1 = get_object_or_404(Word, word=left)
    w2 = get_object_or_404(Word, word=right)
    puzzle = get_object_or_404(Puzzle, left=w1, right=w2)
    return puzzle_show(request, puzzle)

def puzzle_random(request):
    puzzle = Puzzle.objects.all().order_by('?')[:1].get()
    return puzzle_show(request, puzzle)


def puzzle_get(request):
    from puzzles.factory import PuzzleFactoryException, generate_puzzle
    try:
        p = generate_puzzle()
        return redirect(p)
    except PuzzleFactoryException:
        pass
    return render(request, 'puzzles/generate_error.html' )


# answer form

class PuzzleForm(forms.Form):
    answer = forms.CharField(max_length=100, min_length=3,
        required=True, label='')

def answer(request, puzzle_id):
    from django.shortcuts import redirect
    puzzle = get_object_or_404(Puzzle, pk=puzzle_id)
    if request.method == 'POST':
        form = PuzzleForm(request.POST)
        if form.is_valid():
            # process form.cleaned_data
            w = form.cleaned_data['answer']
            word, created = Word.objects.get_or_create(word=w)
            answer = puzzle.answer(word);
            link1, link2 = answer.get_links()
            template_args = {'puzzle': puzzle, 'answer': answer,
                'left_link': link1, 'right_link': link2}
            if answer.is_verified:
                return render(request, 'puzzles/answer.html', template_args)
            elif answer.is_rejected: 
                return render(request, 'puzzles/rejected.html', template_args)
            else:
                return render(request, 'puzzles/unverified.html', template_args)
        else: # redisplay form with error notification:
            return render(request, 'puzzles/puzzle.html',
                        {'puzzle': puzzle, 'form': form })

    return redirect(puzzle)

# creation action

def puzzle_create(request, word):
    w = get_object_or_404(Word, word=word)
    if request.method == 'POST':
        f_left  = request.POST['left']
        f_right = request.POST['right']
        # TODO: all this could go wrong and exceptions need to be caught!
        w_left  = Word.objects.get(word = f_left)
        w_right = Word.objects.get(word = f_right)
        p = Puzzle.objects.create(left = w_left, right = w_right)
        a = Answer.objects.create(puzzle = p, answer = w)
        return render(request, 'puzzles/create.html', { 'word': w, 'puzzle': p, 'answer': a } )
    return render(request, 'puzzles/create.html', { 'word': w } )

puzzles/templates/puzzles/answer.html
<h1>Right answer!</h1>
<p class="explanation">The puzzle was:</p>
<p class="puzzle"><i><a href="{% url 'puzzles:puzzle_by_words' puzzle.left puzzle.right  %}">{{puzzle}}</a></i></p>
<p class="explanation">Your answer was:</p>
<h2>{{ answer.answer }}</h2>
<p class="explanation">as in:</p>
<ul><li>{{puzzle.left}} {{answer.answer}}{% if left_link.annotation %}
    <p class="annotation">{{ left_link.annotation }}</p>
{% endif %}</li>
<li>{{answer.answer}} {{puzzle.right}}{% if right_link.annotation %}
    <p class="annotation">{{ right_link.annotation }}</p>
{% endif %}</li></ul>
<p class="explanation">
This puzzle has now been attempted {{puzzle.attempts}} times.
This answer has been given {{answer.attempts}} times.
    {% if puzzle.answers.count > 1 %}
        There are {{ puzzle.answers.count }} known answers.
    {% endif %}
</p>
<p class="links"><a href="{% url 'puzzles:index' %}">Back to puzzles</a>
<a href="{% url 'puzzles:random' %}">Random puzzle</a>
<a href="{% url 'puzzles:get' %}">New puzzle</a>
</p>

puzzles/templates/puzzles/create.html
<h1>Puzzle creation</h1>
{% if puzzle %}
<h2>Thank you</h2>
<p>Your puzzle <a href=""><i>{{ puzzle }}</i></a> has been created!</p>
{% endif %}
<form action="{% url 'puzzles:create' word.word %}" method="post">
{% csrf_token %}
<!-- <input type="hidden" name="word" value="{{word.word}}" /> -->
<select name='left'>
{% for w in word.predecessor.available %}
    <option value="{{w.word}}">{{w}}</option>
{% endfor %}
</select>
<b>{{word.word}}</b>
<select name='right'>
{% for w in word.successor.available %}
    <option value="{{w.word}}">{{w}}</option>
{% endfor %}
</select>
<input type="submit" name="Submit" />
</form>

puzzles/templates/puzzles/generate_error.html
<h1>Something went wrong...</h1>
<p>Sorry, we couldn't generate a puzzle for you at this time. Possibly
the database is exhausted (in which case, why not
<a href="{% url 'learn:index' %}">teach me something</a>?) or maybe you
were just unlucky this time.</p>
<p class="links"><a href="{% url 'puzzles:index' %}">Back to puzzles</a>
<a href="{% url 'puzzles:random' %}">Random puzzle</a>
<a href="{% url 'puzzles:get' %}">New puzzle</a>
</p>

puzzles/templates/puzzles/index.html
{% if puzzles %}
    <h1>Missing Links</h1>
        <ul>
        {% for puzzle in puzzles %}
                <li><a href="{% url 'puzzles:puzzle_by_words' puzzle.left puzzle.right %}">{{puzzle}}</a></li>
        {% endfor %}
        </ul>
<p class="links"><a href="{% url 'puzzles:random' %}">Random puzzle</a>
<a href="{% url 'puzzles:get' %}">Get puzzle</a>
</p>
{% else %}
        Sorry, we don't have any puzzles to load.
{% endif %}

puzzles/templates/puzzles/puzzle.html
<form action="{% url 'puzzles:answer' puzzle.id %}" method="post">
{% csrf_token %}
<p><b>{{puzzle.left}}</b>
    {% for field in form %}
        {{ field }}
    {% endfor %}
<b>{{puzzle.right}}</b></p>
{% if form.errors %}
    <ul>
    {% for error in form.answer.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
{% endif %}
<input type="submit" value="Submit" />
</form>
<p class="links"><a href="{% url 'puzzles:index' %}">Back to puzzles</a>
<a href="{% url 'puzzles:random' %}">Random puzzle</a>
<a href="{% url 'puzzles:get' %}">New puzzle</a>
</p>

puzzles/templates/puzzles/rejected.html
<h1>That's not quite right...</h1>
<p class="explanation">The puzzle was:</p>
<p class="puzzle"><i><a href="{% url 'puzzles:puzzle_by_words' puzzle.left puzzle.right  %}">{{puzzle}}</a></i></p>
<p class="explanation">Your answer was:</p>
<h2>{{ answer.answer }}</h2>
<p class="explanation">as in:</p>
<ul>
<li>{{puzzle.left}} {{answer.answer}}</li>
<li>{{answer.answer}} {{puzzle.right}}</li>
</ul>
<p class="explanation">
Unfortunately this answer has been rejected for some reason. I will try to
shed a bit more light on why this is.</p>

<p class="explanation">
{% if answer.answer.is_rejected %}
Your answer <i>{{answer.answer}}</i> is a rejected word.
Sorry about that.
There are several reasons why words may be rejected - for example, if they are
misspellings of words, or word particles rather than full words in themselves,
or certain kinds of trademark. Rejected words are never allowed to appear in
puzzles or make links with other words.
{% else %}
    The first part <i>({{puzzle.left}} {{answer.answer}})</i>
    {% if left_link.is_rejected %}
has been rejected. There are many, many reasons why this could be the case.
Often it's because this combination of words does not have a <i>specific</i>
meaning - for example, <i>hot dog</i> refers specifically to a kind of food,
while <i>hot cat</i> just refers to a feline. The English language is in
constant flux and meaningful new combinations crop up all the time: it may
just be that we havwn't got around to learning this one yet.
    {% else %}
        looks fine.
    {% endif %}
    {% if left_link.annotation %}
        </p><p class="annotation">
            {{left_link.annotation}}
        </p>
    {% endif %}
    </p><p class="explanation">
    The second part <i>({{answer.answer}} {{puzzle.right}})</i>
    {% if right_link.is_rejected %}
        {% if left_link.is_rejected %}
            has also been rejected in the same way.
        {% else %}
has been rejected. There are many, many reasons why this could be the case.
Often it's because this combination of words does not have a <i>specific</i>
meaning - for example, <i>hot dog</i> refers specifically to a kind of food,
while <i>hot cat</i> just refers to a feline. The English language is in
constant flux and meaningful new combinations crop up all the time: it may
just be that we havwn't got around to learning this one yet.
        {% endif %}
        {% if right_link.annotation %}
        </p><p class="annotation">
            {{right_link.annotation}}
        </p>
        {% endif %}
    {% else %}
looks fine.
    {% endif %}
{% endif %}
</p>
<p class="links">
<a href="{% url 'puzzles:index' %}">Back to puzzles</a>
<a href="{% url 'puzzles:puzzle_by_words' puzzle.left puzzle.right  %}">Try the same puzzle again</a>
<a href="{% url 'puzzles:random' %}">Random puzzle</a>
<a href="{% url 'puzzles:get' %}">New puzzle</a>
</p>

puzzles/templates/puzzles/unverified.html
<h1>I'll have to check that...</h1>
<p class="explanation">The puzzle was:</p>
<p class="puzzle"><i><a href="{% url 'puzzles:puzzle_by_words' puzzle.left puzzle.right  %}">{{puzzle}}</a></i></p>
<p class="explanation">Your answer was:</p>
<h2>{{ answer.answer }}</h2>
<p class="explanation">as in:</p>
<ul>
<li>{{puzzle.left}} {{answer.answer}}</li>
<li>{{answer.answer}} {{puzzle.right}}</li>
</ul>
<p class="explanation">
{% if answer.answer in puzzle.left.successor.verified %}
The first part <i>({{puzzle.left}} {{answer.answer}})</i> makes sense, but I
couldn't understand the second part, <i>{{answer.answer}} {{puzzle.right}}</i>.
That isn't a word, phrase or two-word idiom that I know about.
{% elif answer.answer in puzzle.right.predecessor.verified %}
The second part <i>({{answer.answer}} {{puzzle.right}})</i> makes sense, but I
couldn't understand the first part, <i>{{puzzle.left}} {{answer.answer}}</i>.
That isn't a word, phrase or two-word idiom that I know about.
{% else %}
But I don't recognise either of <i>{{puzzle.left}} {{answer.answer}}</i> or
<i>{{answer.answer}} {{puzzle.right}}</i> as words, phrases or idioms.
{% endif %}
</p>
<p>
This is great news! One of the ways I learn new things is by seeing new and
different answers to puzzles. I've recorded your answer for a Word Wrangler
to review. If it's approved, then it will be recognised as a new answer to this
puzzle, and the new word links will be used in the creation of new puzzles.
If on the other hand it's rejected for some reason (usually because one of the
links suggested does not have a <i>specific</i> meaning) then I'll be able
to explain the problem in a more detailed way on this very page.
</p>
<p class="links">
<a href="{% url 'puzzles:index' %}">Back to puzzles</a>
<a href="{% url 'puzzles:puzzle_by_words' puzzle.left puzzle.right  %}">Try the same puzzle again</a>
<a href="{% url 'puzzles:random' %}">Random puzzle</a>
<a href="{% url 'puzzles:get' %}">New puzzle</a>
</p>