learn/urls.py
from django.conf.urls import patterns, url

from learn import views

urlpatterns = patterns('',
        # eg: /learn/
        url(r'^$', views.index, name='index'),
        # eg: /learn/word/
        url(r'^(?P<word>[a-zA-Z]+)/$', views.learn_word, name='learn_word'),
)

wordlinks/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wordlinks.views.home', name='home'),
    # url(r'^wordlinks/', include('wordlinks.foo.urls')),

    url(r'^learn/', include('learn.urls', namespace='learn')),
    url(r'^words/', include('words.urls', namespace='words')),
    url(r'^puzzles/', include('puzzles.urls', namespace='puzzles')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

words/urls.py
from django.conf.urls import patterns, url

from words import views

urlpatterns = patterns('',
        # eg: /words/
        url(r'^$', views.index, name='index'),

        # eg: /words/5/
        # url(r'(?P<word_id>\d+)/$', views.detail_id, name='detail'),

        # eg: /words/example/
        url(r'(?P<word_string>[a-z]+)/$', views.detail_string, name='detail'),
)

learn/models.py
from django.db import models

# Create your models here.

learn/views.py
from django import forms
from django.shortcuts import render, get_object_or_404
from django.forms import widgets
from words.models import Word, WordLink, validate_word

WORD_ORDER_CHOICES = (
    (0, 'Before'), #  BLANK some_word
    (1, 'After'),  #  some_word BLANK
)

class LearnForm(forms.Form):
    word = forms.CharField(widget = widgets.HiddenInput, max_length=100, \
        min_length=3, required=True, validators = [validate_word] )
    submission = forms.CharField(max_length=100, min_length=3, required=True, \
        label='', validators = [validate_word])
    word_order = forms.ChoiceField(choices = WORD_ORDER_CHOICES, \
        widget = widgets.HiddenInput)
    
def learn_word(request, word):
    from django.shortcuts import redirect
    context = {}
    if request.method == 'POST':
        form = LearnForm(request.POST)
        if form.is_valid():
            # process form.cleaned_data
            word_order = form.cleaned_data['word_order']
            f_root_word = form.cleaned_data['word']
            f_submission = form.cleaned_data['submission']
            
            root_word = Word.objects.get(word=f_root_word)
            submission, created = Word.objects.get_or_create(word=f_submission)

            new_link = False
            link = ""
            if word_order == '0':
                link = submission.word + " " + root_word.word
                if not root_word.predecessor.filter(word=submission).exists():
                    link, new_link = WordLink.objects.get_or_create(
                        predecessor = submission, successor = root_word)
            else:
                link = root_word.word + " " + submission.word
                if not root_word.successor.filter(word=submission).exists():
                    link, new_link = WordLink.objects.get_or_create(
                        predecessor = root_word, successor = submission)

            # drop through here to set up another learning opportunity
            # TODO: I'm sure this is the wrong way to do things!
            context['learned'] = True
            context['link'] = link
            context['last_order'] = word_order
            context['last_word'] = root_word
            context['last_submission'] = submission
            context['link_created'] = new_link
            context['word_created'] = created
        else:
            # form was invalid, so redisplay with errors.
            return render(request, 'learn/index.html',
                {'form': form })

    import random
    order = str(random.randint(0, 1))
    form = LearnForm( initial = { 'word': word, 'word_order': order } )
    context['form'] = form

    return render(request, 'learn/index.html',
        context )


def index(request):
    from django.shortcuts import redirect
    w = Word.objects.verified.order_by('?')[0]
    return redirect('learn:learn_word', word = w.word)

learn/templates/learn/index.html
<h1>Learning mode</h1>
{% if learned %}
    <h2>Thank you!</h2>
    {% if word_created or link_created %}
        <p><i><b>NB:</b> New words and word links <b>MUST BE VERIFIED</b> by an
        administrator before they will appear on the site. Approval may take some
        time. Thank you for your patience and understanding.</i></p>
    {% endif %}
    {% if word_created %}
        <p><b>I learned the word <a href="{% url 'words:detail' last_submission.word %}"><i>{{last_submission}}</i></a>!</b></p>
    {% elif last_submission.is_rejected %}
        <p><b>Unfortunately, <a href="{% url 'words:detail' last_submission.word %}"><i>{{last_submission}}</i></a> was rejected.</b>
            Perhaps it is a popular misspelling or typo; or perhaps it is
            a word particle such as <i>-ing</i> or <i>-ful</i> that doesn't
            form a proper English word by itself.
        </p>
    {% endif %}
    {% if link_created %}
        <p>I learned a new link between words: <i>{{ link }}</i>!</p>
    {% else %}
        I was already aware of the link <i>{{ link }}</i>. What do you make
        of this one, though?
    {% endif %}
{% endif %}
<h2>Teach me something...</h2>
<form action="{% url 'learn:learn_word' word=form.word.value %}" method="post">
{% csrf_token %}
{% if form.word_order.value = '0' %}
    <div>{{ form.submission }} {{ form.word.value }}</div>
{% else %}
    <div>{{ form.word.value }} {{ form.submission }}</div>
{% endif %}
{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}
{% if form.is_bound and form.errors %}
    {{ form.errors }}
{% endif %}

<input type="submit" value="Submit" />
<a href="{% url 'learn:index' %}">Give me a different word!</a>
</form>